# Generated by Django 4.2.7 on 2025-09-19 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('purchase', 'Purchased Item'), ('project', 'Project Access'), ('document', 'Document'), ('service', 'Service'), ('consultation', 'Consultation')], max_length=20)),
                ('access_level', models.CharField(choices=[('view', 'View Only'), ('download', 'Download Allowed'), ('edit', 'Edit Allowed'), ('full', 'Full Access')], default='view', max_length=10)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='dashboard/files/')),
                ('external_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('download_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
